version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: samplepassword
      MONGO_INITDB_DATABASE: moviemetadatadb

volumes:
  mongodata:
    