version: '3.8'

services:
  zmqclient:
    image: zmqclient
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5010:5000
      - 4444:4444
    volumes:
      - .:/app
    restart: always