version: "3.8"
services:
    go-service-grpc-book:
        build: ./services/go-service-grpc-book
        ports:
          - 4000:4000
        environment: 
          - PORT=4000
    nodejs-service-timestamp:
        build: ./services/nodejs-service-timestamp
        ports:
          - 4010:4010
        environment: 
          - PORT=4010
    nodejs-express-service-zipcodes:
        build: ./services/nodejs-express-service-zipcodes
        ports:
          - 4020:4020
        environment: 
          - PORT=4020
          - ZIPCODE_API_KEY=Pu63zKEoCgidbnau62EUcYl0xKqTm8fsPLRH4nf2N6EyJLMpc6UJ8JiDXMJU1rJV
    zmqclient:
      image: zmqclient
      build:
        context: .
        dockerfile: ./services/python-zmqclient-service/Dockerfile
      volumes:
        - ./services/python-zmqclient-service:/app
      restart: always
    zmqserver:
      image: zmqserver
      build:
        context: .
        dockerfile: ./services/python-zmqserver-service/Dockerfile
      environment:
        - FLASK_ENV=development
      ports:
        - 4030:5010
      volumes:
        - ./services/python-zmqserver-service:/app
      restart: always      