version: '3.8'

services:
  zmqserver:
    image: zmqserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLASK_ENV=development
    ports:
      - 5010:5000
      - 4444:4444
    volumes:
      - .:/app
    restart: always