### Get root
GET http://localhost:5000 HTTP/1.1

### Get healthcheck
GET http://localhost:5000/healthz HTTP/1.1

### Get URLs
GET http://localhost:5000/urls HTTP/1.1

### Wrong URL
GET http://localhost:5000/rwrw HTTP/1.1