version: '3.8'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.5.8-focal
    restart: always
    environment:
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 13306:3306